name: socialgene_nf

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Strictly pinned versions
  - conda-forge::python==3.11
  - bioconda::seqkit==2.5.1
  - hcc::aspera-cli==3.9.6 # bin/download_ncbi_taxon.sh
  - bioconda::entrez-direct==16.2 # bin/download_ncbi_taxon.sh
  - bioconda::hmmer==3.3.2
  - bioconda::mmseqs2==15.6f452
  - bioconda::diamond==2.1.8
  - conda-forge::ncbi-datasets-cli=15.27
  - bioconda::tabix==1.11
  - bioconda::samtools==1.18
  # Not strictly pinned versions
  - conda-forge::pip>=23.1.2
  - conda-forge::biopython>=1.79
  - conda-forge::numpy>=1.24
  - conda-forge::coreutils>=9.3
  - conda-forge::sed>=4.8
  - conda-forge::rsync>=3.2.7
  - conda-forge::wget>=1.20
  - bioconda::grep>=3.4
  - conda-forge::git>=2.41
  - conda-forge::pigz>=2.6
  - conda-forge::gzip>=1.12
  - conda-forge::openjdk==17.0.3 # required by neo4j
  - conda-forge::procps-ng>=4.0 # required by nextflow
  - conda-forge::unzip>=6.0
  - conda-forge::bc>=1.07.1
  - bioconda::ncbi-genome-download>=0.3.3
