name: socialgene_nf

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::python>=3.10
  - conda-forge::pip
  - conda-forge::biopython>=1.79
  - conda-forge::numpy
  - bioconda::seqkit>=2.3.0
  - hcc::aspera-cli
  - bioconda::entrez-direct
  - bioconda::hmmer>=3.3.2
  - bioconda::mmseqs2>=13.45111
  - bioconda::diamond>=2.0.15
  - conda-forge::ncbi-datasets-cli>=13.28
  - bioconda::ncbi-genome-download>=0.3.1
  - bioconda::tabix>=1.11
  - bioconda::samtools>=1.16.1
  - conda-forge::coreutils
  - conda-forge::sed
  - conda-forge::rsync
  - conda-forge::wget
  - bioconda::grep
  - conda-forge::git
  - conda-forge::pigz>=2.6
  - conda-forge::gzip >=1.12
  - conda-forge::openjdk
  - pip:
      #- /Users/chase/Documents/github/socialgene/sgpy
      - git+https://github.com/socialgene/sgpy.git@cd0b6489405abe3c1b1fefb46c96f1cb29bc0ea1
      - git+https://github.com/socialgene/antismash_gbk_to_table.git@e8d8b9f83eae0305550cd3b32e53c2a11f32c69e
