lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
  files_exist:
    - .github/workflows/branch.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - .travis.yml
    - docs/usage.md
    - docs/output.md
    - docs/README.md
    - docs/images/nf-core-socialgene_logo_light.png
    - docs/images/nf-core-socialgene_logo_dark.png
    - docs/images/nf-core-autometa_logo.png
    - conf/test.config
    - conf/test_full.config
    - assets/multiqc_config.yml
    - assets/nf-core-sgnf_logo_light.png
    - docs/images/nf-core-sgnf_logo_light.png
    - docs/images/nf-core-sgnf_logo_dark.png
  readme: false
  actions_ci: false
  nextflow_config: false

repository_type: pipeline
