repository_type: pipeline
lint:
  files_unchanged:
    - assets/email_template.html
    - modules/nf-core/custom/dumpsoftwareversions/main.nf
    - .github/workflows/linting.yml
    - .github/workflows/branch.yml
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-sgnf_logo_light.png
    - docs/images/nf-core-sgnf_logo_light.png
    - docs/images/nf-core-sgnf_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/test.config
    - conf/test_full.config
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  template_strings:
