name: socialgene_nf

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::python==3.10
  - bioconda::hmmer==3.3.2
  - pip
  - rsync # needed for nextflow
  - numpy
  - wget
  - pip:
    - /home/chase/Documents/github/kwan_lab/socialgene/sgpy
