name: socialgene_nf

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::python==3.10
  - bioconda::hmmer==3.3.2
  - pip
  - rsync # needed for nextflow
  - numpy # can't install numpy with just pip if using python 3.9
  - wget
  - pip:
      - /media/bigdrive2/chase/socialgene/2022_07_13/sgpy
