name: socialgene_hmmer

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::procps-ng>=4.0 # required by nextflow
  - conda-forge::bash # required by nextflow
  - conda-forge::python==3.11
  - conda-forge::wget
  - conda-forge::rsync
  - conda-forge::coreutils
  - conda-forge::curl
  - conda-forge::gzip
