name: sgnf-hmmer

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - bioconda::hmmer==3.4
  - conda-forge::coreutils
  - conda-forge::gzip >=1.12
  - procps-ng # required by nextflow
