contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #socialgenebro channel"
    url: https://nfcore.slack.com/channels/socialgenebro
    about: Discussion about the nf-core/socialgenebro pipeline
