contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #builder channel"
    url: https://nfcore.slack.com/channels/builder
    about: Discussion about the nf-core/builder pipeline
