---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(ggplot2)
library(skimr)
```

```{r}
all_hmms = fread("/home/chase/Documents/socialgene_outdir/temp/all_hmms.tsv")
all_hmms[, basedir := sapply(strsplit(rel_path, "/"), function(x) x[[1]]) ]
skim(all_hmms)
```

```{r}
ggplot(all_hmms) +
  geom_boxplot(aes(x = basedir, y = model_length)) +
  xlab("Source of HMM") +
  ylab("HMM Length") +
  ggtitle("HMM profile length")
```


```{r}
ggplot(all_hmms) +
    geom_boxplot(aes(x = basedir, y = log10(model_length))) +
    xlab("Source of HMM") +
    ylab("HMM Length (log10)") +
  ggtitle("Log10 HMM profile length")
```



---

Same thing but look at only the "unique" that were kept





```{r}
hmm_input_for_sg = fread("/home/chase/Documents/socialgene_outdir/temp/unique_hmms.tsv")
hmm_input_for_sg[, basedir := sapply(strsplit(rel_path, "/"), function(x) x[[1]]) ]

```

```{r}

combined_data = rbind(
  cbind(hmm_input_for_sg[ , c('model_length',  'basedir')], "data_source" = "hmm_input_for_sg"),
  cbind(all_hmms[ , c('model_length',  'basedir')], "data_source" = "all_hmms"))



ggplot(combined_data) +
  geom_boxplot(aes(x = basedir, y = model_length)) +
  facet_wrap(~data_source)
```


```{r}
ggplot(a) +
    geom_boxplot(aes(x = basedir, y = log10(model_length))) +
    xlab("Source of HMM") +
    ylab("HMM Length (log10)") +
  ggtitle("Log10 HMM profile length")
```


NOt much noticable chane
