name: socialgene_nf

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::python>=3.10
  - bioconda::hmmer>=3.3.2
  - bioconda::seqkit>=2.3.0
  - hcc::aspera-cli
  - bioconda::entrez-direct
  - bioconda::mmseqs2==13.45111
  - bioconda::diamond>=2.0.15
  - conda-forge::ncbi-datasets-cli>=13.28
  - conda-forge::pigz>=2.6
  - conda-forge::biopython>=1.79
  - bioconda::ncbi-genome-download>=0.3.1
  - conda-forge::sqlite>=3
  - git
  - pip
  - rsync
  - numpy
  - wget
  - grep
  - conda-forge::gzip >=1.12
  - pip:
      - /home/chase/Documents/github/kwan_lab/socialgene/sgpy
