name: Publish Docker images to DockerHUb and GitHub Container Registry

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      packages: write
      contents: read
    strategy:
        matrix:
          env:  [{image:'chasemc2/sgnf-sgpy', context:'dockerfiles/sgpy'},{image:'chasemc2/sgnf-antismash', context:'dockerfiles/antismash'},{image:'chasemc2/sgnf-hmmer_plus', context:'dockerfiles/hmmer_plus'},{image:'chasemc2/sgnf-hmmer', context:'dockerfiles/hmmer'},{image:'chasemc2/sgnf-minimal', context:'dockerfiles/minimal'}]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUBPAT }}
      - name: Log in to Github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/socialgene
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            my-docker-hub-namespace/${{ matrix.env.IMAGE_CONTEXT.image }}
            ghcr.io/socialgene/${{ matrix.env.IMAGE_CONTEXT.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.env.IMAGE_CONTEXT.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
