# Remove commented lines to also upload to github container registry
name: Publish Docker images to DockerHub and GitHub Container Registry
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build_and_push_sgnf_base:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUBPAT }}
      - name: Build Docker images
        run: |
            cd dockerfiles
            pushd multistage
            docker build --target sgnf-hmmer -t chasemc2/sgnf-hmmer:${{ github.event.release.tag_name }} .
            docker build --target sgnf-hmmer-plus -t chasemc2/sgnf-hmmer-plus:${{ github.event.release.tag_name }} .
            docker build --squash --target sgnf-sgpy -t chasemc2/sgnf-sgpy:${{ github.event.release.tag_name }} .
            popd

            pushd antismash
            docker build . -t chasemc2/sgnf-antismash:${{ github.event.release.tag_name }} .
            popd

            pushd prokka
            docker build . -t chasemc2/sgnf-prokka:${{ github.event.release.tag_name }} .
            popd

            pushd minimal
            docker build . -t chasemc2/sgnf-minimal:${{ github.event.release.tag_name }} .
            popd

      - name: Push Docker images
        run: |
            docker push chasemc2/sgnf-hmmer:${{ github.event.release.tag_name }}
            docker push chasemc2/sgnf-hmmer-plus:${{ github.event.release.tag_name }}
            docker push chasemc2/sgnf-sgpy:${{ github.event.release.tag_name }}
            docker push chasemc2/sgnf-antismash:${{ github.event.release.tag_name }}
            docker push chasemc2/sgnf-prokka:${{ github.event.release.tag_name }}
            docker push chasemc2/sgnf-minimal:${{ github.event.release.tag_name }}
